version: 2.1

jobs:
  
  install_dependencies:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: circleci/node:latest
    steps:
      # Replace this with steps to deploy to users
      - checkout          
      - run:
          name: install dependencies
          command: npm install
workflows:
  deploy_workflow:
    jobs:
      - install_dependencies