version: 2.1

jobs:
  
  install_dependencies:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: circleci/node:latest
    steps:
      # Replace this with steps to deploy to users
      - checkout          
      - run:
          name: install dependencies
          command: npm install

  build_docker_image:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_HUB_UN/circlecirepo:latest .
  push_dockerhub:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: push image to docker hub
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_UN --password-stdin
            docker push $DOCKER_HUB_UN/circlecirepo:latest
workflows:
  deploy_workflow:
    jobs:
      - install_dependencies
      - build_docker_image
      - push_dockerhub:
          requires:
            - build_docker_image